### ISSUE TITLE
Error: More than 10% of the data file is corrupt when I install the world

### ISSUE THREAD

**Issue by MidoIdona** [Damaskian/Foundry-Degenesis#1]
When I install the world via world.json I get the following error:

_Uncaught (in promise) Error: More than 10% of the data file is corrupt, the wrong beforeDeserialization hook may be used. Cautiously refusing to start NeDB to prevent dataloss
    at Persistence.treatRawData (C:\Program Files\FoundryVTT\resources\app\node_modules\nedb\lib\persistence.js:242:11)
    at C:\Program Files\FoundryVTT\resources\app\node_modules\nedb\lib\persistence.js:281:38
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)_

Link used for world.json : https://raw.githubusercontent.com/Damaskian/Foundry-Degenesis/main/world.json
FoundryVTT ver. : 0.6.6
Sandbox System Builder ver. : 0.3.9
Dice So Nice! ver. : 2.0.4

**Comment by Damaskian** [comment]
Clear the world and try again with the Manifest URL :D

**Comment by MidoIdona** [comment]
New update resolve the issue. 👌
